### ISSUE TITLE
Enable Github Actions version Updates

### ISSUE THREAD

**Issue by aht007** [edx/edx-arch-experiments#161]
We would like to automate the process of updating Github Actions versions. 

In this regard two approaches came forward.

- Enabling `Dependabot` for generating PRs to upgrade Action versions.
- Using `github-actions-version-updater` Action which is an open source Project.

**Dependabot advantages:**

1. Maintained by GitHub itself, very unlikely to go unmaintained
2. Captures changelog for the changes since version currently in use directly in the PR description
3. Shows percentage of other upgrading projects that avoided CI breakage after the upgrade

Sample PR: https://github.com/openedx/edx-repo-health/pull/307
Docs:

* https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/enabling-and-disabling-dependabot-version-updates
* https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates

**Github-actions-version-updater advantages:**

1. Possible to batch multiple action upgrades into 1 PR
2. Open source Python implementation, possible to contribute and/or fork to customize for ourselves
3. Captures the link to Github release notes of new release and adds to the PR description

Sample PR: https://github.com/aht007/edx-platform/pull/3
Homepage: https://github.com/saadmk11/github-actions-version-updater

**2u-Internal ticket:** https://2u-internal.atlassian.net/browse/BOM-3347

**Comment by jmbowman** [comment]
We moved this historical Jira ticket to a GitHub Issue so we could collect some feedback from other maintainers in the community on a preferred approach.  We're basically ready to go forward with either solution (one discovered in the process of implementing the other one).

**Comment by feanil** [comment]
I'm a fan of the dependabot approach and have already enabled it on a few repos that I'm maintaining.  I prefer the separate PRs because it allows us to make changes more granular and not accept it all or nothing.  The PRs are pretty small and easy to review so having a few more doesn't cost anything in my mind.

**Comment by jmbowman** [comment]
I think our main concern with the dependabot approach is PR fatigue; there are definitely teams and times where there will be a strong tendency to just ignore the PRs if they come in with any non-trivial frequency, because there's mental overhead in even starting to look at any PR that isn't directly required for the current top-priority projects.  It may still be the right way to go given the other listed advantages, but for example we have a much better track record of merging weekly Python package upgrade PRs (which catch everything outdated that isn't specifically pinned) than more frequent but smaller Renovate JS PRs (which currently tend to sit around for months even when utterly trivial).

On the other hand, the worst likely outcome of an action upgrade is breaking CI until we revert, so it's not like JS package upgrades which can potentially trigger site breakage impacting millions of users.  Might be easier to advocate for a "merge first, ask questions later" policy for these, possibly even auto-merging when tests pass.

**Comment by feanil** [comment]
+1 to auto-merging if tests pass. If this results in breakage in production then our tests aren't testing something important that they should be testing.  So I think it would encourage investment in the right things.

**Comment by jmbowman** [comment]
Summarizing the conversation above for clarity:

* Let's go with the dependabot checks for now.
* If the volume of dependabot PRs becomes a problem, we can set them up to auto-merge if tests pass.

**Comment by jmbowman** [comment]
Note that a similar Dependabot feature is now available for shared workflows, we may also want to use that: https://github.blog/changelog/2023-03-13-dependabot-updates-support-reusable-workflows-for-github-actions/

**Comment by jmbowman** [comment]
Before completing this, let's make sure that the parts of https://2u-internal.atlassian.net/wiki/spaces/AT/pages/402784776/How+to+enable+Dependabot+for+Github+actions+version+updates which are relevant for people outside 2U get moved to a page in the Open edX Confluence.

**Comment by UsamaSadiq** [comment]
Created new Document under Open edX Confluence for the community with related guideline: https://openedx.atlassian.net/wiki/spaces/AC/pages/3779985421/How+to+enable+dependabot+for+Github+actions+version+updates
