### ISSUE TITLE
Update GHA runner config if necessary

### ISSUE THREAD

**Issue by jmbowman** [edx/edx-arch-experiments#207]
I spotted this in the GitHub changelog feed: https://github.blog/changelog/2023-01-31-github-actions-job-summary-updates/ .  It looks like a configuration change may be needed to our settings for which hosts are allowed to communicate with our self-hosted runners.  Please determine if any changes are needed, and make them if necessary.  Feel free to create an SRE ticket if necessary.  We have until July 31st to make any necessary changes.

**Comment by UsamaSadiq** [comment]
After going through the documentation in detail and considering we haven't faced any issue within the last three months after the suggested deadline, we can assume that no change is needed on our self-hosted runners. 
I'd close this issue for now since we don't need to update any configurations. We can go back to these config changes if we face any issue in the future.
