### ISSUE TITLE
Ownership transfer: large cookie alerts

### ISSUE THREAD

**Issue by dianakhuang** [edx/edx-arch-experiments#412]
Follow up to https://github.com/edx/edx-arch-experiments/issues/372

AC:
- [ ] Arch-BOM no longer gets alerts for large cookies

Stuff to do:
- [ ] Set (latest possible) date for transfer to new team
- [ ] Inform new team of transfer
- [ ] If necessary, set up transfer meeting
- [ ] If necessary, move alerts + runbook to new team

**Comment by rgraber** [comment]
Blocking this pending more discussion between Jasper and David to determine the best team

**Comment by robrap** [comment]
[questions]
- Can we document what team and product person are the new owners of cookie monitoring?
- Should openedx/core/djangoapps/cookie_metadata be owned by this team to make ownership more clear?
  - This app currently contains Middleware for renaming an existing cookie.
  - Should the rest of the cookie monitoring code be moved to this app?
- Most importantly, as the larger ecommerce effort continues to add tools to [edx.org](http://edx.org/) domain, who needs to be kept in the loop on the cookie size problems, and how this project might impact that? (I'll ping David about this when he is feeling better.)

Also:
- As current owners - maybe we should continue to look into alerts, rather than ignoring them. I think we've taken the pressure off ourselves of moving this work - and now no one is looking into issues.
- This ticket should either no longer be blocked (because David is no longer in this process), or the reason for marking it as blocked should be updated.

**Comment by rgraber** [comment]
As of 10/13 we are still waiting for Jasper to get back to us

**Comment by rgraber** [comment]
The alerts are now owned by search-discover under Ashley Smith.

**Comment by rgraber** [comment]
Closing this as we no longer get the alerts. We are still going to present at a search-discovery meeting but this is no longer being worked on actively.
