### ISSUE TITLE
[On Call] Ensure that the ownership sync scripts handle refactoring in edx-platform

### ISSUE THREAD

**Issue by dianakhuang** [edx/edx-arch-experiments#45]
edx-platform code was refactored to move code out of `common/lib`. It seems like the new locations do not exist in the ownership spreadsheet. We would like to ensure that our automation catches changes to these new top level edx-platform libraries (like `xmodule`).

Context: [this discussion in Slack](https://edx-internal.slack.com/archives/CG44QNLSC/p1658349007147519)

Acceptance Criteria:
1. Ensure that the ownership sync code handles these new libraries.
2. Ensure that the new libraries end up in the ownership spreadsheet.
3. Ensure that the code owner mappings in New Relic are also updated for these libraries.

**Comment by robrap** [comment]
@dianakhuang:
1. This code was not a djangoapp brought into New Relic, so nothing to do there.
2. Just adding the directory seemed to not break anything. I think there is a low priority bug for detected these types of directory changes, so I opened a separate ticket: https://github.com/edx/edx-arch-experiments/issues/46.

I'm going to close this ticket, since these directory is now in the spreadsheet.
