### ISSUE TITLE
Remove remaining deprecated codecov package usage

### ISSUE THREAD

**Issue by jmbowman** [edx/edx-arch-experiments#506]
Seeing https://github.com/openedx/credentials/pull/2298 go by, I realized that we still have a few packages using the obsolete NPM & PyPI packages for codecov.  These should be removed, and the code switched over to the new coverage data upload workflow if that hasn't already been done.  A search for `"codecov` in the repo health dashboard yielded:

* edx/gesmarter-api-clients (PyPI)
* edx/learning-assistant (PyPI)
* openedx/django-splash (PyPI)
* openedx/edx-when (PyPI)
* openedx/frontend-app-profile (NPM)
* openedx/help-tokens (PyPI)

**Comment by zubairshakoorarbisoft** [comment]
I've created 5 PR for the PyPI and not for [openedx/frontend-app-profile](https://github.com/openedx/frontend-app-profile/blob/zshkoor/remove-codecov-package/package.json) because codecov does not exist in `package.json`:

1. https://github.com/openedx/edx-when/pull/224
2. https://github.com/edx/learning-assistant/pull/43
3. https://github.com/openedx/django-splash/pull/158
4. https://github.com/openedx/help-tokens/pull/174
5. https://github.com/edx/getsmarter-api-clients/pull/22
