### ISSUE TITLE
[Alerts] Dump NewRelic data around alerts and policies

### ISSUE THREAD

**Issue by dianakhuang** [edx/edx-arch-experiments#564]
Acceptance Criteria
- [ ] A spreadsheet with all of this data, hopefully with ids
    - ensure that there is enough information for owners to decide whether or not they want to migrate it
    - try to include the existing workflow information
    - ~~Note: implementation includes synthetics~~

Implementation Details
- Get a dump of the existing New Relic policies and alerts
- ~~Get a dump of the existing New Relic synthetic tests (ping checks, api checks, etc)~~
- maybe if we can get all the detail (not just links to the thing)
- feel free to try exporting via terraform
- edx-django-utils/monitoring has scripts that we have used for this sort of dump before
- Can we also get the notifications and workflows?

**Comment by dianakhuang** [comment]
Dumped alert data: https://docs.google.com/spreadsheets/d/14pSgimMnnrpvKdag0JFvlfkj9Y_HVO8atDaBdpor_c4/edit?usp=sharing

**Comment by dianakhuang** [comment]
The data above is incomplete in that it only includes the nrql alert conditions. Discussion with NewRelic support revealed that we might not be able to access the other conditions using the NerdGraph API we were using and we would need to access that data using the REST API instead. This is being deprioritized as we work to get Datadog set up and instrumented for our systems.

**Comment by robrap** [comment]
@alangsto: 
1. This ticket had Synthetics listed, but I've crossed that out. We can ticket that separately. You are welcome to do that work if you wish.
2. Tim did have the idea of doing a terraform export to gather this data from NR. That is something you could try if it gets you what you want faster, or gets the appropriate workload information, etc. This is just an idea. I don't know if it will just slow you down at this point.

**Comment by robrap** [comment]
@alangsto: This ticket is in-progress because you are working on it, but maybe we should groom it anyway?

Also copying in notes from Slack:

Additional thoughts:

1. Could you add whether or not each alert condition is enabled? I think that would help in decision making around migration.
2. I noticed that [this alert policy](https://onenr.io/0qwyx19qpQn) doesn't have anything under notifications. I didn't know that was possible. Does that mean this alert only shows up in the New Relic UI? That might also be a useful piece of data for deciding importance for migrating.
3. We might need an SRE specific thread for some questions:
  a. [This same alert policy](https://onenr.io/0qQagvq2pR1) has one "Disk Usage % High" alert. It is unclear to me whether these infrastructure alerts are redundant to any existing or automated alerts that SRE sets up.
  b. Related, who will be notified for these alerts? Will it be SRE? Service owning teams? Does this affect who is responsible for migrating? Historically, SRE has owned this, but this question was brought up somewhere. This potentially needs discussion between SRE, Eng Managers, and Product.
  c. I know I wrote this up before, but I haven't seen it move forward. Are you ok owning this, or do you want Simon or Jeremy R. to own pushing this forward? Either way, it probably needs to happen sooner rather than later. Thank you.

**Comment by robrap** [comment]
@alangsto: Should this be closed? Thanks.

**Comment by alangsto** [comment]
Yes, I believe this is complete.
