### ISSUE TITLE
[Infra] [Discovery] terraform and Confluent

### ISSUE THREAD

**Issue by robrap** [edx/edx-arch-experiments#67]
With new events and teams onboarding, I'm concerned with not having our config as code.

AC:
- [x] Answer questions and understand if there are any blockers to migrating to using terraform.
- [ ] Either make the switch, ticket follow-up work for making the switch, or document why we think it is wise to delay further.

Notes:

* Experiment with terraform for Confluent config.
  * Can/should we use it for topics? ACLs?
  * Can we transition an existing topic to terraform?
  * Same questions for clusters, etc.
* Determine when and if terraform would be the right solution. Or, should we create custom scripts for config as code (could be explored in another ticket, or discussed with Degrees/John Ford.) Or, should we stick with manual setup longer (seems scary)?

**Comment by robrap** [comment]
This may or may not need Becca's eSRE-fu.

**Comment by dianakhuang** [comment]
General Documentation for later reference: 

https://docs.confluent.io/cloud/current/clusters/terraform-provider.html

https://registry.terraform.io/providers/confluentinc/confluent/latest/docs

**Comment by dianakhuang** [comment]
Okay, I think it makes sense to use this in order to manage clusters, ACLs, and topics, since we have terraform resources for all of those. We would only need to generate and configure the correct API keys in order to manage this in Atlantis.

It seems like one thing that we may be able to make use of in order to migrate to Terraform is their [Resource Importer](https://registry.terraform.io/providers/confluentinc/confluent/latest/docs/guides/experimental-resource-importer). It's still marked as experimental, but (a) it is a read-only operation to prevent issues and (b) we should be able to modify the output to ensure it matches our expectation.

I'm not sure how we can migrate just one cluster vs. all the clusters at the same time, because terraform seems to be a more complete solution, but I'll talk to SRE about our previous terraform integrations and for more information on terraform in general.

**Comment by dianakhuang** [comment]
We have tested importing with a service user that has EnvironmentAdmin access to edx-dev, and we've been able to pull resources from both cloud (Confluent.cloud).

There is a proposal to have a new dev environment called edx-terraform-dev that is managed by terraform. We will be doing initial testing on this environment to ensure terraform works the way we won't.

**Comment by dianakhuang** [comment]
note: renaming a topic destroys the old one and creates a new one.

**Comment by robrap** [comment]
@dianakhuang:
1. Could you create an internal Slack channel (e.g. `#tech-confluent` or something like that)?
2. Should we add a reference to this ticket in https://2u-internal.atlassian.net/wiki/spaces/AT/pages/432603238/Event+Bus+Terraform+Decisions?
3. Can we start a conversation in `#tech-confluent` with John Ford to review our decisions?
4. What is needed to get the last decision out of "Proposed" state?
Thanks. Let me know if you disagree with any of this.

**Comment by rgraber** [comment]
closing as the work is now with SRE
