### ISSUE TITLE
Deployment plan for catalog event to Production

### ISSUE THREAD

**Issue by robrap** [edx/edx-arch-experiments#68]
* Document deployment (or roll-out) plan for turning on happy path in Production.
* Implement roll-out plan (may need to be a separate ticket, depending on timing/findings)

Questions:
- Should we turn off after deployment, until sad-path or other Production readiness work from the Production milestone is complete?
- How many phases?
- Will publishing the event and consuming the event be split? How will this affect things if the consumer starts picking up a big backlog of older published events?
- What is the minimal QA required? A separate task exist for this.
- What is the communication plan? Note: We already started announcements. We need to discuss with TNL as well, since they are the eventual owners of the publishing side. Both TNL and Phoenix should understand and agree to the sad-path results as well.
- Observability requirements? Different for different phases?

**Comment by rgraber** [comment]
Recording some answers we established, as well as my own opinions

- We don't think we'll need to turn it off after deployment since it has RCM as a backup (discussed as a team)
- One (discussed as a team)
- No, we can turn them on at the same time. If we have to turn the consumer off for a while before turning it back on we can discuss whether to remove the 'offset.earliest' bit (my opinion)
- Already tasked
- We will follow the How We Announce plan. I vote we move any sad-path discussion to the sad path epic so we don't block ourselves unnecessarily. (my opinion)

I also don't think we need to create another roll out plan. We already have tasks for enabling everything in production, a QA ticket, and directions in How We Announce for where to announce, as well as an ADR around why we chose this particular use case. Together those cover pretty much the extent of the roll-out work and this feels like unnecessary overhead.

**Comment by rgraber** [comment]
Actual plan:
1. Announce event publishing (follow How We Announce), making sure in particular TNL knows it's coming
2. Turn on publishing by adding the correct configs and toggling SEND_CATALOG_INFO_SIGNAL to True
3. [Optional] Turn off publishing
4. [Optional] If we are worried about the amount of backlog generated (which I don't think we will be, even if we leave publishing on), update the consumer to process from the latest offset instead of the earliest
5. Announce event consuming
6. Turn on consuming with  https://github.com/edx/edx-arch-experiments/issues/47

**Comment by rgraber** [comment]
Also should bump event-bus-kafka to 1.0.0 since it will be used in prod.
