### ISSUE TITLE
Improve PR Review Process

### ISSUE THREAD

**Issue by iamsobanjaved** [edx/edx-arch-experiments#81]
The current process of Python requirements upgrade PRs is that the team is tagged for the review of the PR once the PR is created successfully, or when there is a failure in the creation of PR, the team is alerted through an email. As we want everyone in the team to have an equal share of responsibility, we want to have a rotation of the person doing that responsibility each week. My suggestion is to use Opsgenie for this purpose. Try to come up with the approach and get reviewed by the team before implementing that approach.

**A/C**
- Get a review on the approach by the team
- Implement that approach 
- Update the workflows in arch-owned repositories (if needed)
- Document the agreed approach in Confluence

**Comment by UsamaSadiq** [comment]
After discussing with the team, we've decided to choose a team on-call person manually. The on-call person will be responsible to review the requirements upgrade PRs daily. 
Once the Opsgenie credentials are created, we can move forward with the next process.

@jmbowman we'd like to request for arbi-bom's Opsgenie credentials to be created with our 2U onelogin credentials. Should we create a support ticket for this?

**Comment by jmbowman** [comment]
I think @robrap is working on restoring OpsGenie access for the Arbi-BOM team; Robert, could you please let them know when this is done?  (Or let me know if you need any help getting it set up.)

**Comment by robrap** [comment]
Hello @UsamaSadiq. The OneLogin card for OpsGenie is the "Atlassian (Atlassian Cloud)" card. The OpsGenie url is https://2u-internal.app.opsgenie.com/alert/list. If that combo doesn't let you in, you will need to create a HelpDesk request for your team as you had noted. Maybe copy me and Jeremy on the HelpDesk email so we can see what happens. Thank you and good luck.

**Comment by UsamaSadiq** [comment]
Hi @robrap 
Soban and I both tried logging in to the mentioned url through the OneLogin Card but we still get redirected to the login page instead. 
I believe our only option is to create a HelpDesk request ticket. I'll email the help desk team with the issue and loop you both in.

**Comment by robrap** [comment]
@UsamaSadiq: Did you try from an incoginito window to ensure you don't have a cookie or something else cached that is causing the issue? Other than that, I'd try HelpDesk. Thanks.

**Comment by iamsobanjaved** [comment]
I was usually trying from Chrome, just tried with both incognito mode and Firefox and the behavior is still the same. I explained the procedure below.

### Breakdown:

- Open this https://2u-internal.app.opsgenie.com/alert/list
- Redirection to the OpsGenie login page (used 2U email for login here)
- Redirection to the Atlassian login page (used 2U email for login here)
- Redirection to OneLogin for SAML
- Redirection to https://2u-internal.app.opsgenie.com/alert/list
- Again Redirection to the OpsGenie login page

**Comment by robrap** [comment]
Ok. That’s useful context for the helpdesk ticket. Can you copy me on the helpdesk email? Thanks.

**Comment by UsamaSadiq** [comment]
Hi @robrap 
Sent email to the 2U helpdesk for this issue and tagged you on the email as well. Thanks.

**Comment by rgraber** [comment]
I sent a follow-up email to help desk and was told that some people on the list are not showing any OneLogin activity at all. They requested  that everyone
1. log out of Atlassian
2. log in to OneLogin
3. Launch Atlassian from the tile
4. If you get an error and the "Try Logging in" button, hit that
5. Try to go to OpsGenie

If we can confirm that this flow doesn't fix it they'll escalate to Saas Ops.

**Comment by UsamaSadiq** [comment]
Hi @rgraber 
Most of the arbi-bom team members tried the steps mentioned above but still no one could access OpsGenie so we'll need to escalate this issue further. 
Logging into an incognito window and trying these steps after logging in again also didn't work. 
As for no OneLogin activity of some members of our team, they have created help desk issues for their OneLogin access. Some of the issues have been resolved but few members are still facing some issues in accessing all services from OneLogin & VPN. 

Could you please escalate this issue with the help desk team? Thanks.

**Comment by robrap** [comment]
@rgraber: I'll connect with @UsamaSadiq on this as on-call.

**Comment by UsamaSadiq** [comment]
Whole `arbi-bom` team got access to opsgenie. Following are the email addresses of team members associated with respected opsgenie accounts: 

- Awais: aqureshi1@2u.com
- Soban: sjaved@edx.org
- Umar: ukhan@2u.com
- Usama: usadiq@edx.org
- Zubair: zshakoor@2u.com

@jmbowman could you please add all these members in the `arbi-bom` team on opsgenie since some of us aren't part of it on opsgenie yet. 
Once these accounts are all added in the `arbi-bom` team on opsgenie, we'll start following the on-call rotation according the order mentioned in the opsgenie schedule.

**Comment by robrap** [comment]
@UsamaSadiq:
1. I took care of the updates (and removed the email addresses from this ticket).
2. Most of your team already had admin for your team, so you could really self-manage these types of issues in the future. See https://2u-internal.app.opsgenie.com/teams/dashboard/b6fb91e8-a11d-44c2-9bda-3cf8639ff539/members.
3. On https://2u-internal.app.opsgenie.com/teams/dashboard/b6fb91e8-a11d-44c2-9bda-3cf8639ff539/main, find the link that reads "Primary" in order to update your on-call rotation as needed.
4. Note: on that same page, you can use "Add override" to schedule temporary take over of on-call as needed. This feature defaults to putting the logged-in user as the on-call, but you choose a different user, for example if you want someone else to take over your on-call.
5. Finally, feel free to click around and explore, and if you have any questions, ask in Slack or we can set up a meeting.
Good luck!

**Comment by UsamaSadiq** [comment]
Thanks for the guidelines @robrap. I've verified that we've admin access so we can handle such requests on our own in future. I've updated the `opsgenie` rotations to include current members for weekly rotations.

**Comment by UsamaSadiq** [comment]
Improvements suggestions for the `Python Requirements Upgrade` PR review process: 

- `arbi-bom-on-call` person will be responsible to review, fix issues if any, approve and merge the requirements upgrade PRs.
- `arbi-bom` team will use gmail filters to filter out `Python Requirements Upgrade` PRs notifications in the emails to avoid missing any email announcement. 
- A potential step to improve the notification process will be to tag the `arbi-bom-on-call` on the `Python Requirements Upgrade` PRs for review as well if possible.

**Comment by iamsobanjaved** [comment]
Thanks, the document is in draft currently for on-call responsibilities. It will have all details of this too.
